set(NLDCORE_FILES
  src/bitmask.cpp
  src/bitmask.h
  src/bit_matrix.cpp
  src/bit_matrix.h
  src/bitpos.h
  src/bitslice.h
  src/bitslice_data.h
  src/bitslice_pair.h
  src/bitslice_step.h
  src/bitslice_step_data.h
  src/bitslice_twobit_condition.h
  src/cache.h
  src/cache_base.h
  src/cache_manager.cpp
  src/cache_manager.h
  src/carry_step.h
  src/change.cpp
  src/change.h
  src/characteristic.cpp
  src/characteristic.h
  src/condition.cpp
  src/condition.h
  src/condition_container.h
  src/condition_proxy.cpp
  src/condition_proxy.h
  src/condition_word.cpp
  src/condition_word.h
  src/container_condition_proxy.cpp
  src/container_condition_proxy.h
  src/crypto.cpp
  src/crypto.h
  src/dynamic_cache.h
  src/functions.cpp
  src/functions.h
  src/horizontal_condition_word.cpp
  src/horizontal_condition_word.h
  src/index.h
  src/konstant_condition_proxy.cpp
  src/konstant_condition_proxy.h
  src/latex_print_visitor.cpp
  src/latex_print_visitor.h
  src/linear_conditions.cpp
  src/linear_conditions.h
  src/linear_matrix.cpp
  src/linear_matrix.h
  src/linear_step.h
  src/linear_step_data.h
  src/linkable_condition_proxy.h
  src/logfile.h
  src/managable_cache.cpp
  src/managable_cache.h
  src/mask_condition_proxy.cpp
  src/mask_condition_proxy.h
  src/pair.h
  src/printable.cpp
  src/printable.h
  src/print_config.cpp
  src/print_config.h
  src/print_matrix.cpp
  src/print_matrix.h
  src/print_visitor.cpp
  src/print_visitor.h
  src/probability.h
  src/probability_matrix.h
  src/probability_output.cpp
  src/probability_output.h
  src/probability_output_matrix.cpp
  src/probability_output_matrix.h
  src/propagate.h
  src/propagate_twobit.h
  src/propagate_twobit_output.cpp
  src/propagate_twobit_output.h
  src/row.h
  src/search.cpp
  src/search.h
  src/search_stack.cpp
  src/search_stack.h
  src/static_cache.h
  src/step.h
  src/step_data.h
  src/step_update.h
  src/text_io_format.cpp
  src/text_io_format.h
  src/tinyset.h
  src/twobit_condition.h
  src/twobit_container.cpp
  src/twobit_container.h
  src/utils.h
  src/virtual_condition_proxy.cpp
  src/virtual_condition_proxy.h
  src/word_container.h
  src/xml_config.cpp
  src/xml_config.h
)
